### ISSUE TITLE
鼠须管用户求实例/教程

### ISSUE THREAD

**Issue by bosconb** [lotem/rime-octagram-data#2]
对八股文插件能达到的效果很感兴趣，但看了介绍，自己还是不会配置。已经加载了搜狗的百万级词库，不知道有没有必要装这个？

**Comment by lotem** [comment]
[用法](https://github.com/lotem/rime-octagram-data#%E7%94%A8%E6%B3%95) 在 README 裏有介紹

**Comment by bosconb** [comment]
> [用法](https://github.com/lotem/rime-octagram-data#%E7%94%A8%E6%B3%95) 在 README 裏有介紹

謝謝大佬，用上了！
