### ISSUE TITLE
BINTRAY HAS BEEND EPRECATED

### ISSUE THREAD

**Issue by theodoruszq** [lotem/rime-octagram-data#4]
无法下载语言模型，能否放置于Github等位置。

**Comment by theodoruszq** [comment]
https://jfrog.com/distribution/?bintrayRD=1

**Comment by Nautiluski** [comment]
这个链接也无法下载，请问能不能在某个地方重新发布并更新一下readme？谢谢！

**Comment by iDvel** [comment]
@Nautiluski 
在 hans 和 hant 分支里面有。

**Comment by Nautiluski** [comment]
@iDvel 
谢谢。我找不到hans和hant分支，请问能给个链接吗？不过我通过搜索“rime+hant+gram"这样的关键词，找到了一些gram文件，但是缺hans bgc的版本（不知道是不是本来就没有），而且也不知道我找到的是不是最新的。

**Comment by iDvel** [comment]
@Nautiluski 
在仓库里点击 `master` 就可以切换到。
<img width="396" alt="image" src="https://user-images.githubusercontent.com/14658234/145662387-2818c11e-c1cd-4ee1-b93e-945fd06b1803.png">

**Comment by Nautiluski** [comment]
@iDvel 
正在下载，太感谢了！ReadMe应该更新一下！
